apiVersion: app.ibm.com/v1alpha1
kind: Channel
metadata:
  name: app-channel
  namespace: {{LAB_NAMESPACE}}
spec:
  gates:
    annotations:
      dev-ready: approved
  pathname: {{LAB_NAMESPACE}}
  sourceNamespaces:
  - {{LAB_NAMESPACE}}
  type: Namespace
