apiVersion: app.ibm.com/v1alpha1
kind: Subscription
metadata:
  labels:
    app: lab-apps
  # Required. The name of the subscription resource to create.
  name: app-subscription
  # Required. The namespace resource to use for the subscription.
  namespace: {{LAB_NAMESPACE}}
spec:
  # Required. The namespace/name of the channel for the subscription.
  channel: {{LAB_NAMESPACE}}/app-channel
  placement:
    clusters:
    - name: {{KIND_CLUSTER_NAME}}
    - name: {{AWS_CLUSTER_NAME}}
