LAB_NAMESPACE="cp4mcm-lab"
CP4MCM_BASE_URL="https://icp-console.10.0.10.2.nip.io"
AWS_ACCESS_KEY_ID=""
AWS_SECRET_ACCESS_KEY=""
AWS_REGION="us-east-2"
AWS_CLUSTER_NAME="my-cluster-eks"
KIND_CLUSTER_NAME="my-cluster-kind"
